[workspace]
members = ["libraries/*", "kernel"]

[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = true
panic = 'unwind'
incremental = true
codegen-units = 16
rpath = false

[profile.release]
lto = true