[package]
name = "do-not-enter"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["framebuffer"]

[profile.release]
lto = true

[features]
default = []
bsp_rpi3 = []
bsp_rpi4 = []

[[bin]]
name = "kernel"
path = "src/main.rs"

[dependencies]
# alloc-cortex-m = "0.4.2"
# seq-macro = "0.3.0"
cortex-a = "7.4.0"
framebuffer = { version = "0.1.0", path = "framebuffer" }
spin = "0.9.4"
tock-registers = "0.7.0"
