[toolchain]
channel = "nightly-2022-07-22"
components = ["cargo", "clippy", "llvm-tools-preview", "rustfmt", "rust-src", "core", "compiler_builtins", "alloc"]
targets = [ "aarch64-unknown-none-softfloat" ]
profile = "default"