[toolchain]
channel = "nightly"
components = ["cargo", "clippy", "llvm-tools-preview", "rustfmt", "rust-src"]
targets = [ "wasm32-unknown-unknown", "aarch64-unknown-none-softfloat" ]
profile = "default"