[build]
target = "aarch64-unknown-none-softfloat"

[unstable]
build-std = ["core", "std", "proc_macro", "compiler_builtins", "alloc"]

[target.'cfg(target_os = "none")']
runner = "target/kernel_test_runner.sh"